package update_17;


/**
 *  Record doesn't support extension so they are implicitly final
 *  Record can implement interfaces
 *  we can define member function
 *  can have canonical constructor in compact presentation
 * */

interface NamedRecord{

    default String fullName(String providedName)
    {
        return getClass().getName()+": "+providedName;
    }
}

record NormalRecord(
        String name,
        Integer recordId) implements NamedRecord
{
    // constructor assignment will be generated by compact presentation
    public NormalRecord
    {
        if(name == null)
            throw  new IllegalArgumentException("Name must be given for a user record");

    }

    public String fullName(){
        return fullName(name);
    }

    public static void main(String... args){

    }
}


